package com.qd.peiwen.dcsframework.enmudefine;

public enum  RNEventType {
    TEXT_INPUT_STARTED,
    TEXT_INPUT_FAILURED,
    INPUT_EVENT_SUCCESSED,
    VOICE_RECOGNIZE_STARTED,
    VOICE_RECOGNIZE_FAILURED,
    VOICE_RECOGNIZE_SUCCESSED,
    ON_RECEIVE_TEXT_CARD,
    ON_RECEIVE_LIST_CARD,
    ON_RECEIVE_SERVICE_CARD,
    ON_RECEIVE_STANDARD_CARD,
    ON_RECEIVE_IMAGE_LIST_CARD,
    ON_RECEIVE_PHONE_LIST_CARD,
    ON_RECEIVE_SERVICE_LIST_CARD,
    ON_RECEIVE_SMSMESSAGE_LIST_CARD,
    ON_RECV_TRAIN_TICKET,
    ON_RECV_FLIGHT_TICKET
}
